ci: harden Gradle workflows
Signed-off-by: Sergey Khokhlov <skhokhlov@users.noreply.github.com>

diff --git a/.github/workflows/ci-publish.yaml b/.github/workflows/ci-publish.yaml
--- a/.github/workflows/ci-publish.yaml
+++ b/.github/workflows/ci-publish.yaml
@@ -1,10 +1,3 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
-# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle
-
 name: Publish CI
 
 on:
@@ -13,7 +6,6 @@ on:
 
 permissions:
   contents: read
-  packages: write
 
 jobs:
   build:
@@ -34,16 +26,26 @@ jobs:
             17
             25
             21
-          cache: "gradle"
 
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
+
+      - name: Validate release tag
+        env:
+          RELEASE_TAG: ${{ github.event.release.tag_name }}
+        run: |
+          project_version="$(./gradlew -q properties --property version | sed -n 's/^version: //p')"
+          expected_tag="cyclonedx-gradle-plugin-${project_version}"
+          if [[ -z "${project_version}" || "${RELEASE_TAG}" != "${expected_tag}" ]]; then
+            echo "::error::Release tag '${RELEASE_TAG}' does not match project version '${project_version}' (expected '${expected_tag}')."
+            exit 1
+          fi
 
       - name: Build with Gradle
         run: ./gradlew build -i
 
       - name: Publish to Gradle portal
-        run: |-
-            ./gradlew publishPlugin \
-            -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} \
-            -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
+        env:
+          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
+          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
+        run: ./gradlew publishPlugins
